EktaFlow/docent-base

.gitignore
package-lock.json

- Add additional library & caching directories to .gitignore
- Commit package-lock.json

Update gitignore, add package-lock.json

---

src/app/app.module.ts
src/components/topbar/topbar.html
src/components/topbar/topbar.scss
src/components/topbar/topbar.ts
src/components/views/views.html
src/components/views/views.ts
src/pages/login/login.ts
src/pages/navigate/navigate.ts
src/pages/questions/questions.html
src/pages/questions/questions.scss
src/pages/questions/questions.ts
src/pages/settings/settings.html
src/pages/settings/settings.module.ts
src/pages/settings/settings.scss
src/pages/settings/settings.ts
src/pages/user-dashboard/user-dashboard.html
src/pages/user-dashboard/user-dashboard.scss
src/pages/user-dashboard/user-dashboard.ts

All design functionally working (except filterMRL)
User Dashboard
Adding Team Members in (Sharing)

Sprint 2 Working Branch for Dominique

---

src/pages/questions/questions.html
src/pages/questions/questions.ts
src/services/gql.service.ts

- Update passing of the questionId to call currentQuestion.questionId, the problem was probably a refactor of the questions page instance vars.
- update questionId conditional in markup
- update gql query string to pull down name and questionId in files of an assessment.

Fix uploaded files display on questions page

---

package.json
src/pages/actionitems/actionitems.html
src/pages/actionitems/actionitems.ts

- bring in xlxs lib
- format data on page, function to export to xls
- add button markup for export

Add .xls export functionality - action items page

---

src/app/app.module.ts
src/pages/edit-assessment/edit-assessment.html
src/pages/edit-assessment/edit-assessment.module.ts
src/pages/edit-assessment/edit-assessment.scss
src/pages/edit-assessment/edit-assessment.ts
src/pages/user-dashboard/user-dashboard.html
src/pages/user-dashboard/user-dashboard.ts
src/services/assessment.service.ts

- bootstrap and create new page as template for assessment edit
- add markup and handler to user dashboard
- add 'custom' function to query an assessment

Add base 'edit-assessment' functionality

---

src/pages/questions/questions.html
src/pages/questions/questions.scss

fixed 'when' formatting so is correct size
fixed spacing of other fields

questions page 'no' fix

---

src/components/file-delete/file-delete.ts
src/pages/acronyms/acronyms.html
src/pages/navigate/navigate.html
src/pages/navigate/navigate.scss
src/pages/navigate/navigate.ts
src/pages/questions/questions.html
src/pages/questions/questions.scss

tablet styling fixed - flex box was a mess

questions page tablet styling & clear buttton on nav page

---

src/app/app.scss
src/components/topbar/topbar.html
src/pages/questions/questions.scss

also minimized qspacer size on questions page

added in quesiton history popover to mobile and styled

---

src/pages/questions/questions.html
src/pages/questions/questions.scss
src/pages/summary/summary.html
src/pages/summary/summary.scss

so that risk assessment is next to question fields

fixed questions page sizing 

---

src/components/import/import.html
src/components/import/import.scss
src/components/views/views.ts

- edit styling,
- remove default input
- add file name when one is selected
- able to export a .mra file
- able to import a .mra file

Fix up import/export feature - new schema

---

src/pages/dashboard/dashboard.html
src/pages/dashboard/dashboard.scss
src/pages/dashboard/dashboard.ts

- Update method to turn the assessment object into the object needed to
display the data for the view.
- Update styling, arrange numbers evenly, make legend flow
horizontally

 Update Dashboard to work w/ new schema, style

---

src/components/helpmenu/helpmenu.html
src/components/helpmenu/helpmenu.scss
src/components/risk-popover/risk-popover.html
src/components/risk-popover/risk-popover.scss
src/components/risk-popover/risk-popover.ts
src/components/thread-popup/thread-popup.ts
src/components/topbar/topbar.html
src/components/topbar/topbar.scss
src/components/topbar/topbar.ts
src/components/views/views.html
src/components/views/views.scss
src/components/views/views.ts
src/pages/actionitems/actionitems.ts
src/pages/dashboard/dashboard.html
src/pages/dashboard/dashboard.scss
src/pages/dashboard/dashboard.ts
src/pages/edit-assessment/edit-assessment.html
src/pages/edit-assessment/edit-assessment.scss
src/pages/edit-assessment/edit-assessment.ts
src/pages/home/home.html
src/pages/navigate/navigate.scss
src/pages/navigate/navigate.ts
src/pages/questions/questions.html
src/pages/questions/questions.scss
src/pages/questions/questions.ts
src/pages/review/review.html
src/pages/user-dashboard/user-dashboard.html
src/pages/user-dashboard/user-dashboard.scss
src/pages/user-dashboard/user-dashboard.ts

Some of the small tasks on the new task list
Cleaning up styling, linking, labels, adding small bits of functionality

Low Hanging Fruit

---

src/components/risk-popover/risk-popover.scss
src/pages/home/home.html
src/pages/home/home.scss
src/pages/user-dashboard/user-dashboard.html

small changes cleaning up and polishing tool

Small cleanup

---

src/pages/home/home.html
src/pages/home/home.scss
src/pages/home/home.ts

toast for notification
styling

Team members

---

src/pages/home/home.ts

added in loadingcontroller and used that to make a loading box after clicking start on start page so as to not have user create multiple assessments

added in loading box for start new page

---

src/components/views/views.html
src/pages/actionitems/actionitems.ts
src/pages/dashboard/dashboard.html
src/pages/dashboard/dashboard.scss
src/pages/dashboard/dashboard.ts
src/pages/home/home.html
src/pages/summary/summary.html
src/pages/summary/summary.scss
src/pages/summary/summary.ts
src/pages/user-dashboard/user-dashboard.html

copy cleanup on multiple pages
also fixed spacing on a couple pages (too close/too far from topbar)

Text cleanup

---

src/pages/risk-report/risk-report.html
src/pages/risk-report/risk-report.scss
src/pages/risk-report/risk-report.ts

importing the correct info
displaying the correct info
calculating risk score
using risk score to change color of text and to toggle on/off the extra risk div with greatest impact, risk response and mmp summary

finished risk report for now

---

src/components/question-history-popover/question-history-popover.html
src/components/question-history-popover/question-history-popover.ts
src/components/register/register.html
src/components/register/register.scss
src/components/report-info-card/report-info-card.html
src/components/report-info-card/report-info-card.scss
src/components/report-info-card/report-info-card.ts
src/components/risk-popover/risk-popover.html
src/components/risk-popover/risk-popover.scss
src/pages/actionitems/actionitems.html
src/pages/actionitems/actionitems.module.ts
src/pages/edit-assessment/edit-assessment.html
src/pages/questions/questions.ts
src/pages/risk-report/risk-report.ts
src/pages/summary/summary.html
src/pages/summary/summary.ts

fixed question history popover console errors and displays "question has not been answered"
included non level questions in xls report on risk report page
changed matrix-row on risk popover so that the inner html wouldnt be deleted
only showing extra questions table when extra questions have been answered on risk summary
remove ability to delete team members in edit assessment

Testing 2 15

---

src/components/add-team-members-pop-over/add-team-members-pop-over.html
src/components/add-team-members-pop-over/add-team-members-pop-over.ts

- Add additional disabled button && conditional to flip when user clicks
to add a team member. EG - can only click the invite button once.

Add disable on click for home add team member

---

package.json
src/pages/dashboard/dashboard.html
src/pages/dashboard/dashboard.ts

- add html2canvas to dependencies
- add id to markup, basic png conversion && saving function
- add class var to prevent multiple clicks

Implement png download for dashboard view

---

src/pages/edit-assessment/edit-assessment.ts
src/services/assessment.service.ts

- Add email team member function to assessment service -- take from the
add team member popover
- change ts file of edit page to accomidate

Update edit page team member add

---

src/pages/summary/summary.html
src/pages/summary/summary.ts

have separate export button for non target level questions table
include MRL in table export

add in second export to XLS button for non level table

---

src/components/do-reset/do-reset.html
src/components/do-reset/do-reset.scss

change styling height to fit form
change text below Reset button to what's on register page
Rules for password

Fix reset page

---

src/pages/edit-assessment/edit-assessment.ts

- on closing the edit assessment page, refresh UserDash
- edit bug w/ 1 team member ( wrong .length #)
- move add member toast on edit to top w/ others

Make some tweaks and bugfixes to edit assessment page

---

src/pages/actionitems/actionitems.html
src/pages/criteria/criteria.html
src/pages/edit-assessment/edit-assessment.html
src/pages/faqs/faqs.scss
src/pages/navigate/navigate.html
src/pages/risk-report/risk-report.html
src/pages/settings/settings.html
src/pages/user-dashboard/user-dashboard.html

changed any spot that said scope to additional information
always showing greatest impact / risk response / mmp summary on risk report even if risk score is under 12 or whatever

changing text

---

src/components/login/login.html
src/components/login/login.scss

- Changed use of height units from vw to %.

Bug Fix: Fixed responsive sizing bug due to hardsetting viewsize for logins.

---

.gitignore
cypress.json
cypress/integration/dod-resource-link.js
cypress/support/commands.js
src/components/helpmenu/helpmenu.html
src/components/mobile-nav-popover/mobile-nav-popover.html

Add DoD resource to mobile and web-desktop. Also adds corresponding tests

Dp3 190: DoD resource update and test

---

package-lock.json
package.json

Feature Update: Updates set-value package to 2.0.1 to fix security risk.

feature/DP3-199-security-update-set-value 

---

src/pages/questions/questions.scss

-Feature Update: modified css for correct flex display on ie11.

feature/DP3-183-ie11-question-title-text-alignment 

---

src/services/constants.js

- Changed staging to docenttest

BugFix: Renamed docentaccount name in constants.js

---

src/pages/dashboard/dashboard.ts
src/pages/risk-report/risk-report.ts

MRL summary & Detailed Risk Report page both now downloading reports again

Fix exporting reports

---

src/pages/actionitems/actionitems.ts
src/pages/review/review.ts
src/pages/summary/summary.ts

exported reports show all mrls -- does not include filtering yet

reports show all MRLs

---

src/pages/user-dashboard/user-dashboard.html
src/pages/user-dashboard/user-dashboard.scss
src/pages/user-dashboard/user-dashboard.ts
src/services/gql.service.ts

can dive deeper into doing a percentage bar, but will take a little more because will have to figure out how to style the divs using variables from the .ts file (color is easy, width is a little harder)

showing % complete on each assessment - just text right now

---

src/app/app.module.ts

@BinSquare when this gets deployed you need to do 
`npm i --save logrocket`

just including app.module and not including package.json - installing log rocket

---

src/app/app.module.ts
src/app/pages/user-dashboard/user-dashboard.page.ts

intercom is working on docent and once we get it live we can add product tours and banners easily
----- make sure to do run this code in the server
`npm install ng-intercom@latest --save`

Install intercom

---

src/app/components/views/views.component.ts

Removed the circular dependency and deprecated imports by removing unneeded/deprecated code.

Refactor: Removing circular dependency and deprecated imports.

---

src/app/pages/login/login.page.html

forgot to make a PR and merge in

add link to home page when not logged in

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/views/views.component.html
src/app/components/views/views.component.ts
src/app/pages/comprehensive/comprehensive.module.ts
src/app/pages/comprehensive/comprehensive.page.html
src/app/pages/comprehensive/comprehensive.page.scss
src/app/pages/comprehensive/comprehensive.page.ts

added comprehensive report to the reports tab for users
added export feature

Add comprehensive report

---

package-lock.json
src/app/app.module.ts
src/app/pages/dashboard/dashboard.page.html
src/app/pages/dashboard/dashboard.page.ts
src/app/services/html2canvasservice.service.ts
src/index.html

accidentally merged previous version of this branch and then reverted because i did not want it merged yet
fixes the Download Image button (using html2canvas package) for MRL Summary Report - package was not working with Ionic 4/5 the typical way. 
new Html2Canvas Service has been added

fix download image for MRL Summary report

---

src/app/components/file-upload-popover/file-upload-popover.component.html
src/app/components/file-upload-popover/file-upload-popover.component.scss
src/app/components/helpmenu/helpmenu.component.html
src/app/components/json-upload-popover/json-upload-popover.component.html
src/app/components/json-upload-popover/json-upload-popover.component.scss
src/app/pages/questions/questions.page.html

updated help links that go to dodmrl.com
updated UI for file upload buttons
fixed typo for link to remove icon on files on questions

UI fixes sprint XIV

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/services/can-activate.ts
src/app/services/upload.ts

- added service that checks for docent token and stops route if no token
- change header for upload json function

block route to user dashboard if not logged in 

---

src/app/pages/user-dashboard/user-dashboard.page.scss

* fixed spacing for assessment boxes on mobile view

FIX: mobile-wrapper spacing on user-dash landing
